template: Hello, %s!
defaultName: Stranger
nome: central
versao: 1.0
server:
  applicationConnectors:
  - type: http 
    port: 8080
  - type: https
    port: 8443
    keyStorePath: example.keystore
    keyStorePassword: example
    validateCerts: false
  adminConnectors:
  - type: http
    port: 8081